sudo: required
language: go

go:
  - "1.10"

services:
  - docker

go_import_path: "github.com/ibm-messaging/mq-container"

cache:
  directories:
    - downloads

env:
  - DOCKER_DOWNGRADE="echo nothing to be done"
  - DOCKER_DOWNGRADE="sudo apt-get autoremove -y docker-ce && curl -fsSL \"https://apt.dockerproject.org/gpg\" | sudo apt-key add - && sudo apt-add-repository \"deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -cs) main\" && sudo apt-get update && sudo apt-get install docker-engine=1.12.6-0~ubuntu-$(lsb_release -cs)"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - curl https://glide.sh/get | sh
  - sudo curl -Lo /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
  - sudo chmod +x /usr/local/bin/dep

install:
  - echo nothing

script:
  - make deps
  - make vet
  - make build-devserver
  - make build-devjmstest
  - eval "$DOCKER_DOWNGRADE"
  - echo Running $(docker --version)
  - make test-devserver

after_success:
  - go get golang.org/x/lint/golint
  - make lint
