sudo: required
language: go

go:
  - 1.9

services:
 - docker

before_install:
  - curl https://glide.sh/get | sh
  - curl -LO https://github.com/golang/dep/releases/download/v0.3.0/dep-linux-amd64.zip
  - unzip dep-linux-amd64.zip
  - sudo mv dep /usr/local/bin
  - rm dep-linux-amd64.zip

install:
  - echo nothing

before_script:
  - make deps

script:
 - make build-devserver
 - make test-devserver
